name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update -y
      - name: Run build script
        run: |
          if [ -x ./build_cross.sh ]; then
            ./build_cross.sh
          else
            echo "build_cross.sh not found" && exit 1
          fi

